## Reshaping & transposing

In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10,11,12], [13,14,15],[16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:

a2.shape

(2, 3)

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a3.shape

(2, 3, 3)

In [10]:

a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [11]:

a2.shape

(2, 3)

In [12]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [13]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [14]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:

a2.shape

(2, 3)

In [17]:
# Transpose = switches the axis'
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [18]:
a2.T.shape

(3, 2)

In [19]:
a3.shape

(2, 3, 3)

In [20]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [21]:

a3.T.shape

(3, 3, 2)


## Dot product

In [22]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [23]:
mat2


array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [24]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [25]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [26]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [27]:

# Element-wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [28]:
# Dot product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [29]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [30]:

mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [31]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [32]:

mat3.shape

(5, 5)